// Generated by @wisent-ai/docs-cli from a validated docs plan (spis 1.0.0).
// DocPage data module for DocumentationLayout (@wisent-ai/components >= 0.4.0).
// Every block in the source plan carries a verified claim. Do not edit by hand.

export const docPages = [
  {
    "slug": "overview",
    "nav": "Overview",
    "eyebrow": "Getting started",
    "title": "Spis overview",
    "description": "What Spis is and how every record earns its place in the corpus.",
    "sections": [
      {
        "title": "What Spis is",
        "paragraphs": [
          "Spis is an evidence-grade reference corpus: 700 records across 13 interface families, each carrying its source, hashes, provenance class, and measured state.",
          "A record exists only with its evidence. A missing observation is recorded as an evidence gap and is never promoted into prose."
        ]
      },
      {
        "title": "Words this documentation uses",
        "bullets": [
          "`record` — one measured reference: media, source URL, hashes, provenance class, and status.",
          "`provenance class` — how the media was obtained: `local-product-run`, `local-browser-run`, or `upstream-owner-media`.",
          "`evidence gap` — something the corpus does not know, recorded instead of guessed.",
          "`catalog` — one family of records, such as web-app-examples or cli-examples."
        ]
      }
    ]
  },
  {
    "slug": "quick-start",
    "nav": "Quick start",
    "eyebrow": "Getting started",
    "title": "Quick start",
    "description": "Clone the corpus and run your first command in under a minute.",
    "sections": [
      {
        "title": "Run the CLI",
        "code": [
          {
            "label": "clone and run the consistency gate",
            "code": "$ git clone https://github.com/wisent-ai/spis && cd spis\n$ bin/spis\n$ bin/spis catalogs --check"
          }
        ],
        "paragraphs": [
          "`collect-images` and `analyze-structures` need Pillow; every other command runs on the Python standard library."
        ]
      }
    ]
  },
  {
    "slug": "cli-reference",
    "nav": "CLI reference",
    "eyebrow": "Reference",
    "title": "CLI reference",
    "description": "Every `reference` command and what it owns.",
    "sections": [
      {
        "title": "Commands",
        "table": {
          "columns": [
            "command",
            "owns"
          ],
          "rows": [
            [
              "capture",
              "own-product references from installed binaries"
            ],
            [
              "audit-accessibility",
              "accessibility audit of captured references"
            ],
            [
              "collect-images",
              "attributable official imagery"
            ],
            [
              "analyze-structures",
              "panel and layout analysis"
            ],
            [
              "sync-readmes",
              "upstream README snapshots refresh"
            ],
            [
              "analyze-readmes",
              "README corpus structural analysis"
            ],
            [
              "verify",
              "rewrite records to what the bytes prove"
            ],
            [
              "catalogs",
              "regenerate the index; refuses disagreement"
            ],
            [
              "drift",
              "upstream README and URL drift report"
            ]
          ]
        }
      }
    ]
  }
] as const;

export const docsNav = [
  {
    "label": "Getting started",
    "items": [
      {
        "slug": "overview",
        "label": "Overview"
      },
      {
        "slug": "quick-start",
        "label": "Quick start"
      }
    ]
  },
  {
    "label": "Reference",
    "items": [
      {
        "slug": "cli-reference",
        "label": "CLI reference"
      }
    ]
  }
] as const;
